extends RefCounted
class_name RockTilesetCatalog
## Auto-generated by game/tools/slice_rock_tileset.py — do not edit by hand.

const MANIFEST_PATH := "res://assets/tilesets/rocks/manifest.json"

static func all_paths() -> Array[String]:
	var out: Array[String] = []
	for e in load_manifest():
		out.append(str(e.get("path", "")))
	return out

static func by_category(category: String) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for e in load_manifest():
		if str(e.get("category", "")) == category:
			out.append(e)
	return out

static func paths_in_category(category: String, variant: String = "") -> Array[String]:
	var out: Array[String] = []
	for e in by_category(category):
		if variant != "" and str(e.get("variant", "")) != variant:
			continue
		var p := str(e.get("path", ""))
		if p != "":
			out.append(p)
	return out

static func pick_path(rng: RandomNumberGenerator, category: String, variant: String = "") -> String:
	var paths := paths_in_category(category, variant)
	if paths.is_empty():
		return ""
	return paths[rng.randi() % paths.size()]

static func load_manifest() -> Array:
	var f := FileAccess.open(MANIFEST_PATH, FileAccess.READ)
	if f == null:
		return []
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		return []
	var sprites = parsed.get("sprites", [])
	return sprites if typeof(sprites) == TYPE_ARRAY else []
